# openapi2-run.yaml
swagger: '2.0'
info:
  title: test-api-01
  description: Sample API on API Gateway with a Cloud Run backend
  version: 1.0.0
securityDefinitions:
  google_id_token:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://accounts.google.com"
    x-google-jwks_uri: "https://www.googleapis.com/oauth2/v3/certs"
    x-google-audiences: "32555940559.apps.googleusercontent.com"

schemes:
- https
produces:
- application/json
x-google-backend:
  address: https://simple-http-function-tidc3mgixq-uw.a.run.app
paths:
  /hello:
    post:
      summary: Cloud Run hello world
      operationId: hello
      security:
        - google_id_token: []
      responses:
        '200':
          description: A successful response
          schema:
            type: string
